name: flutter_simple_typewriter
description: "A Flutter package that adds a typewriter effect to text fields, enhancing user interface interactivity."
version: 1.0.0
homepage: 

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
